### PR TITLE
Remove unused url_launcher library in geolocator

### LINKED ISSUE #38: Incompatible with Flutter Fire 1.0.0 due to unused url_launcher dependency
## 🐛 Bug Report

Incompatible with Flutter Fire 1.0.0 / null safe releases.

Due to the dependencies using from what I can see is an unused package dependency of: url_launcher: ^5.4.11

In the main geocoding library I couldn't see any code that would use the url_launcher. It is used in the example but that has its own separate pubspec.yaml.

### Expected behavior

Remove the url_launcher dependency as it is unused and therefore fixes the incompatibility.

### Reproduction steps

N/A

### Configuration

**Version:** 1.0.5

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

### PR DESCRIPTION
**Pull request by grahamsmith**
Fixes #38

### CODE REVIEW

**Comment by grahamsmith** [comment]
@mvanbeusekom the failure in geolocator platform interface is because of an unrelated deprecation. What do you normally do in this instance?

**Comment by mvanbeusekom** [comment]
> @mvanbeusekom the failure in geolocator platform interface is because of an unrelated deprecation. What do you normally do in this instance?

No worries I will quickly fix it in a separate PR now, maybe you can then merge it in.

**Comment by mvanbeusekom** [comment]
@grahamsmith I have just fixed the deprecation warnings, if you could rebase on the `develop` branch the problems should go away.

**Review by mvanbeusekom — APPROVED** [review]

**Comment by grahamsmith** [comment]
Done :+1: and thanks for fixing those warning 👍  - was in the middle of it in case but was finding the migration non obvious.

**Comment by grahamsmith** [comment]
@mvanbeusekom new failures are from cocoapods. Unsure how to fix unfortunately.

**Comment by mvanbeusekom** [comment]
@grahamsmith could you rebase once more with the `develop` branch, this should fix the iOS build step.

**Comment by grahamsmith** [comment]
Spotted the merge just pushing now

**Comment by mvanbeusekom** [comment]
Thanks @grahamsmith

**Pull request merged**
