### PR TITLE
Fix compatibility with AGP 8.0

### PR DESCRIPTION
**Pull request by pento**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Bug Fix

### :arrow_heading_down: What is the current behavior?

When upgrading to AGP 8.0, the upgrade fails due to the `geocoding_android` project not having a namespace specified.

### :new: What is the new behavior (if this is a feature change)?

N/A

### :boom: Does this PR introduce a breaking change?

Nope.

### :memo: Links to relevant issues/docs

[flutter/flutter#125181](https://github.com/flutter/flutter/issues/125181), [flutter/flutter#125621 (comment)](https://github.com/flutter/flutter/issues/125621#issuecomment-1525995461), Baseflow/flutter-geolocator#1250

### CODE REVIEW

**Comment by pento** [comment]
@mvanbeusekom Since you seem to be the person who reviews/merges PRs here, I'm pinging you just in case you don't actively monitor this repo. 🙂

**Review by mvanbeusekom — CHANGES_REQUESTED** [review]
Could you also update the `example` project with the current Gradle plugin version? 

This would prove that this fix works.

**Comment by pento** [comment]
Done! It's worth noting that I was running into flutter/flutter#128204, as well. b07adae fixes this particular error by limiting the `url_launcher_android` version to an older one that doesn't have this problem.

I don't know what your preference is for including this kind of workaround, versus waiting for an upstream fix. I've included it for completeness, but can revert it if you'd prefer to wait.

**Review by mvanbeusekom — APPROVED** [review]
Thank you @pento, this looks great!

**Comment by mvanbeusekom** [comment]
@pento, could you rebase with the main branch? I have updated the workflows which should maken sure the CI checks should pass.

**Comment by pento** [comment]
Thank you for handling the rebase and merge, @mvanbeusekom!

**Pull request merged**
