### PR TITLE
Use async API for Android 33+ (#195)

### LINKED ISSUE #195: [Bug]: Android backend needs to switch to the async API
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geocoding/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geocoding/blob/main/geocoding/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS

### Steps to reproduce

The Android `Geocoder` [docs](https://developer.android.com/reference/android/location/Geocoder) say:

> Warning: This API may hit the network, and may block for excessive amounts of time, up to 60 seconds or more. It's strongly encouraged to use the asynchronous version of this API. If that is not possible, this should be run on a background thread to avoid blocking other operations.

### Expected results

Both the calls in the Android backend use the synchronous API, on the UI thread:

```java
return geocoder.getFromLocationName(address, 5);
```

```java
return geocoder.getFromLocation(latitude, longitude, 5);
```

Instead, these should be switched to the asynchronous API, which takes an additional callback parameter of type [`Geocoder.GeocodeListener`](https://developer.android.com/reference/android/location/Geocoder.GeocodeListener).

### Actual results

Currently the blocking API is used.

### Code sample

N/A

### Screenshots or video

N/A

### Version

latest

### Flutter Doctor output

N/A

### PR DESCRIPTION
**Pull request by lukehutch**
Fixes #195 (adds async API support for Android 33+) -- however I can't get the code to build on my machine, so I can't test it!

## Pre-launch Checklist

- [ ] I made sure the project builds.
- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy], or this PR is does not need version changes.
- [ ] I updated `CHANGELOG.md` to add a description of the change.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I rebased onto `main`.
- [ ] I added new tests to check the change I am making, or this PR does not need tests.
- [ ] I made sure all existing and new tests are passing.
- [ ] I ran `dart format .` and committed any changes.
- [ ] I ran `flutter analyze` and fixed any errors.

### CODE REVIEW

**Comment by TimHoogstrate** [comment]
Dear @lukehutch,

Thanks for your input and help. We had some overlapping work while I was working on another issue. So i combined our work into a new PR [PR 197](https://github.com/Baseflow/flutter-geocoding/pull/197) if you don't mind. I was able to test it on Android 29 and Android 34. Now it works as a charm.

Kind regards,

**Comment by lukehutch** [comment]
Awesome, thanks for this. Do you have a release planned sometime soon?

Actually I just noticed this rather heavy-handed decision by Google:

https://apilevels.com/

> targetSdk [must be 33+](https://developer.android.com/google/play/requirements/target-sdk) for new apps and app updates since August 31, 2023.

Since even app updates require this, I believe this means that all support for API < 33 can simply be dropped. Is this a correct assumption?

**Comment by TimHoogstrate** [comment]
@lukehutch,

I think this is partly true because you it is also possible to ship an app outside of the play store. And then it might not de so strict.

Kind regards,

**Comment by lukehutch** [comment]
@TimHoogstrate Makes sense, I forgot there were other app stores :-)  

What does your release schedule look like? Just trying to coordinate some things. Thanks!

**Pull request closed without merging**
